### ISSUE TITLE
Provide values for "offset" and "repeats" via configurable fields for the HM-Dis-EP-WM55

### ISSUE THREAD

**Issue by Strunzdesign** [ioBroker/ioBroker.hm-rpc#208]
Hi,

The EPaper display HM-Dis-EP-WM55 supports two repetition flags for the acoustic signal. The CCU3 allows to specify an amount of repetitions and a delay between two sounds. Having a look in the source code of file "hm-rpc.js" at line 173 and 174 reveals that both parameters and the related logic are already implemented. To test, If I modify the script manually and change "repetitions" to a value of "2", then the next triggered "beep" signal will be played twice. Great!

However, these are only local variables that are not filled with a value gathered from a dedicated entry from the IOBroker settings of the display. It would be great to add both data points as states and to access these states instead of using hard-coded magic values.

My wish: it should be possible to specify the repetition scheme from a Blockly script, just by modification of two additional missing data points.

Versions:
- HomeMatic RPC adaptor 1.10.3
- Script Engine 4.1.12
- ReGaHSS 2.4.12

Regards,
Florian

**Comment by foxriver76** [comment]
Makes sense.

Note: https://github.com/ioBroker/ioBroker.hm-rpc/blob/546fcc5c6c708ae8c54bc0ad9753e79a2d1b227e/hm-rpc.js#L173

**Comment by Strunzdesign** [comment]
Hope it helps: allowed values for the repetitions in the CCU3 GUI are all values from 1 to 15 as well as "unlimited". Allowed values for "delay" are multiples of 10s up to a maximum of 160s.

Thank you very much,
Florian

**Comment by foxriver76** [comment]
Thanks, helps. However, I am not sure how to set unlimited yet.

**Comment by Strunzdesign** [comment]
Hmm, such an enum-like type that offers only the exact values together with 0=Unlimited should do the trick. Use 10 as default for the delay, and for the repetitions choose 1 as the default. Then nobody accidentally gets a loop of unlimited noise.

**Comment by foxriver76** [comment]
Can you please try if https://github.com/ioBroker/ioBroker.hm-rpc/commit/198952c357fd354bb301f5be062e1a20c180ad8a does the trick. It should add two additional states to each EPAPER device. One for OFFSET and another for REPEATS. If these values are filled, they should be used when controlling the EPAPER. When setting a value to OFFSET, the adapter should acknowledge the state change and ensure it is fitting the allowed min max range.

It is recommended and probably necessary, to delete the EPAPER meta data as well as the EPAPER devices once in ioBroker if they already existed before this commit.

**Comment by Strunzdesign** [comment]
Working on it now...

**Comment by Strunzdesign** [comment]
Hi,

ok, thank you very much, here are my test results. Looks great BTW :-)

1. The adaptor crashed immediately. The "data.offset = state ? state.val || 10;" statements are invalid. Fixed it in the patch below.
2. I wanted to keep the previous meta data to watch the migration process fail, but due to the aforementioned debugging I ended up removing the meta data multiple times. If you want, I go back to the vanilla version and update it again to see how a migration without a deletion works.
3. The min value for offset is 10, not zero.
4. The new meta data fields were empty and not filled with proper defaults. This is dangerous as "no value" equals zero for the repetitions which is unlimited.
5. No idea whether my addition of "OPERATIONS: 2" is required... I saw this while debugging, please rate it yourself.

Test results:
- EPAPER_OFFSET = 10, EPAPER_REPEATS = 1: 1 beep, ok
- EPAPER_OFFSET = 10, EPAPER_REPEATS = 9: 9 beeps @ 10s, ok
- EPAPER_OFFSET = 10, EPAPER_REPEATS = 10: 10 beeps @ 10s, ok
- EPAPER_OFFSET = 10, EPAPER_REPEATS = 15: 15 beeps @ 10s, ok
- EPAPER_OFFSET = 10, EPAPER_REPEATS = 16: 15 beeps @ 10s, clipped at 15, ok
- EPAPER_OFFSET = 10, EPAPER_REPEATS = 1000: 15 beeps @ 10s, clipped at 15, ok
- EPAPER_OFFSET = 10, EPAPER_REPEATS = -1: unlimited beeps @ 10s, clipped at 0
- EPAPER_OFFSET = 160, EPAPER_REPEATS = 2: 2 beeps @ 160s, ok
- EPAPER_OFFSET = -1, EPAPER_REPEATS = 2: 2 beeps @ 10s, used 10s
- EPAPER_OFFSET = 2, EPAPER_REPEATS = 2: 2 beeps @ 10s, used 10s

Next steps / ideas:
- No default values appeared, which is dangerous due to 0 reflecting unlimited.
- It is not visible that offset is in range 10...160 in steps of 10, other values may be entered.
- Would an enum-like type fit better than a raw value type?

Here are my modifications:
```
--- hm-rpc.js.1 2019-11-10 19:39:47.834265035 +0100
+++ hm-rpc.js   2019-11-10 20:01:27.934435384 +0100
@@ -325,14 +325,14 @@
 
     promises.push(new Promise(resolve => {
         adapter.getForeignState(`${id}.0.EPAPER_OFFSET`, (err, state) => {
-            data.offset = state ? state.val || 10;
+            data.offset = state ? state.val : 10;
             resolve();
         });
     }));
 
     promises.push(new Promise(resolve => {
         adapter.getForeignState(`${id}.0.EPAPER_REPEATS`, (err, state) => {
-            data.repeats = state ? state.val || 1;
+            data.repeats = state ? state.val : 1;
             resolve();
         });
     }));
@@ -1349,14 +1349,16 @@
             obj.EPAPER_OFFSET = {
                 TYPE: 'number',
                 ID: 'EPAPER_OFFSET',
-                MIN: 0,
-                MAX: 160
+                MIN: 10,
+                MAX: 160,
+               OPERATIONS: 2
             };
             obj.EPAPER_REPEATS = {
                 TYPE: 'number',
                 ID: 'EPAPER_REPEATS',
                 MIN: 0,
-                MAX: 15
+                MAX: 15,
+               OPERATIONS: 2
             }
         }
     }
```

Great work! Regards,
Florian

**Comment by Strunzdesign** [comment]
EPAPER_REPEATS = 0 works as expected (unlimited), forgot to mentioned that.

**Comment by foxriver76** [comment]
Thank you very much for your input. I fixed the silly syntax error and implemented your suggested changes. 

Now states should be created with default values. Offset min adjusted to 10. Also Offset is rounded to next 10. However, code already catched unrounded values.

**Comment by Strunzdesign** [comment]
Hi,

I got an error with offset=20 an repeats=2:

```
error | Error: XML-RPC fault: Failure
error | xmlrpc -> setValue ["3","SUBMIT","0x02,0x0A,0x0A,0x0A,0x0A,0x14,0xC4,0x1C,0xD1,0x1D,0xE19.9,0x16,0xF0,0x03"]

```

Notice the "0xE19.9"...

**Comment by foxriver76** [comment]
If you think, ENUM is more suitable, we can go for the enum. Just means 17 different states.

**Comment by Strunzdesign** [comment]
ENUMs are more suitable for manual editing of the states in the objects view. However, I have problems using them correctly from within Blockly scripts, as I always have to loop up the underlying enum key/iterator. Perhaps I'm using them incorrectly and Blockly provides are more readable way, but to date, I have not found it. So far, no perfect winner... either an ENUM or a number. As the other fields are ENUM-like hex strings(!), my guts feeling tends towards using an ENUM.

**Comment by foxriver76** [comment]
> Hi,
> 
> I got an error with offset=20 an repeats=2:
> 
> ```
> error | Error: XML-RPC fault: Failure
> error | xmlrpc -> setValue ["3","SUBMIT","0x02,0x0A,0x0A,0x0A,0x0A,0x14,0xC4,0x1C,0xD1,0x1D,0xE19.9,0x16,0xF0,0x03"]
> ```
> 
> Notice the "0xE19.9"...

This cannot work properly: https://github.com/ioBroker/ioBroker.hm-rpc/blob/198952c357fd354bb301f5be062e1a20c180ad8a/hm-rpc.js#L218

**Comment by foxriver76** [comment]
Can you try to replace the line by:         
`command = `${command}0xE${parseInt(offset - 1) / 10},0x16,`;`

**Comment by Strunzdesign** [comment]
More errors in the log. To reproduce:

1. The object view shows EPAPER_OFFSET = 10 and EPAPER_REPEATS = 1
2. I update EPAPER_REPEATS = 1
3. One error line is added to the log:

`error | Error: XML-RPC fault: Unknown parameter`

4. I update EPAPER_REPEATS again with 1
5. Two subsequent errors appear in the log:

```
error | Error: XML-RPC fault: Unknown parameter
error | xmlrpc -> setValue ["0","EPAPER_REPEATS",1] number
error | Error: XML-RPC fault: Unknown parameter
```

However, the display acts accordingly! If I fire a "play command" in the object viewer it works. No idea what causes the problem here, the error is not very verbose.

**Comment by foxriver76** [comment]
I know what causes the error, will push a fix asap, just a missing return command.

**Comment by Strunzdesign** [comment]
I still get this with OFFSET=20 and REPEATS=2

xmlrpc -> setValue ["3","SUBMIT","0x02,0x0A,0x0A,0x0A,0x0A,0x14,0xC4,0x1C,0xD0,0x1D,0xE1.9,0x16,0xF0,0x03"]

Is parseInt the correct way to convert an int to a string?

**Comment by Strunzdesign** [comment]
It's a rounding issue...

**Comment by foxriver76** [comment]
Sorry, brackets were wrong. lol meant

```command = `${command}0xE${parseInt((offset - 1) / 10)},0x16,`;```

but more fashioned way:

```command = `${command}0xE${offset / 10 - 1},0x16,`;```

**Comment by Strunzdesign** [comment]
Hehe thanks :-)

Now 20 works as expected, but OFFSET=11 delivers:

`xmlrpc -> setValue ["3","SUBMIT","0x02,0x0A,0x0A,0x0A,0x0A,0x14,0xC4,0x1C,0xD1,0x1D,0xE0.10000000000000009,0x16,0xF0,0x03"]`

Time for an ENUM or an integer-based rounding :-)

**Comment by foxriver76** [comment]
How did you set an OFFSET of 11?

**Comment by Strunzdesign** [comment]
In the object view... even if I enter 1000 then the value keeps there. It is truncated and processed correctly, but the corrected value is not written back here.

**Comment by foxriver76** [comment]
So now this should be fixed ;-)

Iterative process ... :smiling_imp:

**Comment by Strunzdesign** [comment]
With your latest commit, entering an OFFSET of 21 is still allowed, copied back as 21 (red) and results in:

`error | xmlrpc -> setValue ["3","SUBMIT","0x02,0x0A,0x0A,0x0A,0x0A,0x14,0xC4,0x1C,0xD1,0x1D,0xE1.1,0x16,0xF0,0x03"]
`

The missing return statement is here now, but the error messages do still appear:

`error | Error: XML-RPC fault: Unknown parameter`

Still iterating :-)

**Comment by Strunzdesign** [comment]
Full log event:

error | Error: XML-RPC fault: Unknown parameter
error | xmlrpc -> setValue ["0","EPAPER_OFFSET",20] number

**Comment by foxriver76** [comment]
True, sorry cannot work.

**Comment by foxriver76** [comment]
Should now work - attempt nr. 503 :smiling_imp:

**Comment by Strunzdesign** [comment]
Using your latest commit, I removed my meta data again to reimport the device. Now the object editor is borked: it is not possible to enter any value anymore. No ENUM available to select from, still no default values, just empty. Seems that I can enter text here, but a valid numer 10 + pressing enter seems to freeze the field.

**Comment by Strunzdesign** [comment]
... freezes the whole object editor view!

**Comment by Strunzdesign** [comment]
Yeah, that killed the whole IOBroker, even a restart did not help! Reverted to the previos version, that was less aggressive. No problem! That's part of the game :-)

**Comment by foxriver76** [comment]
I cannot explain how this behavior should be the outcome of the latest change.

**Comment by Strunzdesign** [comment]
IOBroker starts eating my CPUs... perhaps some inconstities in the meta data info, or a free running value update loop?

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     ZEIT+ BEFEHL                                                                                                                                         
26858 iobroker  20   0  912056 120896  21488 S  41,4   0,7   0:53.34 iobroker.js-con                                                                                                                                
28237 iobroker  20   0  663112  62724  22188 S  25,8   0,4   0:26.71 io.hm-rpc.1                                                                                                                                    
27750 iobroker  20   0  890728  81688  24032 S  17,2   0,5   0:19.51 io.sql.0                                                                                                                                       
27699 iobroker  20   0  811796 138960  21852 S  15,9   0,8   0:19.01 io.javascript.0

**Comment by foxriver76** [comment]
And going back to the official version solves the cpu issues? I am still not able to explain what causes the problems.

**Comment by Strunzdesign** [comment]
Going 1-2 steps back did not work... but now I have the official file that works. I even have the updated meta data here... still works. It happened with one of the latest commits, perhaps that one that changed the meta data to EPAPER types?

Need more testing, but that change introduced the freezer here.

**Comment by foxriver76** [comment]
And then it freezes when you put a value in one of the States? I will look into it tomorrow but somehow it’s strange.

**Comment by Strunzdesign** [comment]
I confirm, the latest commit is the culprit. I removed the device and restarted with a freshly fetched file each. With the latest commit, it crashes as soon as I enter a value for EPAPER_REPEATS.

https://raw.githubusercontent.com/ioBroker/ioBroker.hm-rpc/81c177e8bf8e5de1ec9391dfc62b3509b42593b6/hm-rpc.js -> works

https://raw.githubusercontent.com/ioBroker/ioBroker.hm-rpc/4ddffac2e8acdb5de52ea807ca79c1a0dfa80cf0/hm-rpc.js -> works

https://raw.githubusercontent.com/ioBroker/ioBroker.hm-rpc/da78fd166282ea8c82d90b909896076b9d3f8233/hm-rpc.js -> latest, crashes

**Comment by foxriver76** [comment]
Is there an error in log?

**Comment by foxriver76** [comment]
Thanks for investigation

**Comment by Strunzdesign** [comment]
... and I have to remove the device to kill all meta data after reverting to the latest good commit... just going back is not enough. Seems that the latest commit poisons the meta data and hinders the previous good commit to work either.

**Comment by Strunzdesign** [comment]
No errors, the whole iobroker goes to a grinding halt.

**Comment by Strunzdesign** [comment]
Seems to be a loop somehow... my SQL adapter got overfed with junk... going to investigate how to clean the mess up.

**Comment by foxriver76** [comment]
Ahhh... lol got it but no longer on my laptop. Problem is, state is set with ack false, triggers the same again and so on ...

**Comment by Strunzdesign** [comment]
Hehe I knew this has an easy cause :-) See you tomorrow, good night! :+1:

**Comment by foxriver76** [comment]
Added the 2 trues via smartphone. Good night and thanks for your patience 😴

**Comment by Strunzdesign** [comment]
Wow, great, that works. That made my day! Good night, again :+1:

**Comment by Strunzdesign** [comment]
Everything works fine, the values update themselves correctly now even if I enter junk, perfect. The only small issue is that there are no default values visibly set after import of the device. That may end up having an infinite series of beeps. I'm ging to test that tomorrow after work. Maybe this is just a glitch with refreshing the entries of a new device, and the correct default value is already there, but invisible.

Thanks again, that was really great!

**Comment by foxriver76** [comment]
Which js-controller version do you use. As far as I remember, there was a 'bug' which did not use the def values. According to changelog it should work with js-controller >= 2.0.2, see https://github.com/ioBroker/ioBroker.js-controller/blob/master/CHANGELOG.md#202-2019-09-17-release-bella, especially 
`(foxriver76) setObject/setObjectNotExists now also sets default value of state after object creation`

**Comment by Strunzdesign** [comment]
Hi,

dumb question, how do I determine the version of js-controller? However, my ioBroker entity was installed from scratch two weeks ago... on nodejs-10.17.0. it is still shiny :-)

**Comment by foxriver76** [comment]
E. g. via cli by typing `iob -v`

You can also find it in admin adapter on tab named `hosts` (maybe needs to be enabled)

**Comment by foxriver76** [comment]
If you are running stable, version is 1.5.14. This would be perfectly fine. I am running this version on my productive environment too.

**Comment by Strunzdesign** [comment]
Hi,

ok, thanks for the hint, I also run stable version 1.5.14. Furthermore, now I added the "hosts" view, I was not aware of it. I started just 4 weeks ago with ioBroker so I am still new to the topic.

Furthermore, some ideas for improvement:
- The EPAPER_TONE values 0xC7:"7", 0xC9:"9", and 0xCA:"A" are useless and should be removed. The CCU3/Raspimatic also shows only the referenced 6 tones + "not in use".
- "offset" is not an optimal name. "interval" or "pause" suits better as it is no initial delay (aka "offset") is meant but a time span between two sounds.
- Plus: "offset" and "repeats" relate to EPAPER_TONE only, so I recommend a bulk renaming of:
- - EPAPER_OFFSET -> EPAPER_TONE_INTERVAL
- - EPAPER_REPEATS -> EPAPER_TONE_REPEATS or better EPAPER_TONE_REPETITIONS (->my favorite)
- - EPAPER_TONE -> EPAPER_TONE (ok as it is) or EPAPER_TONE_TYPE, or EPAPER_TONE_MELODY (->my favorite)

Besides just that, the support for the display is in a really great shape now :+1: 

Regards,
Florian

**Comment by Strunzdesign** [comment]
EPAPER_SIGNAL is also confusing. EPAPER_LED or EPAPER_BLINK would be better.

**Comment by foxriver76** [comment]
We can rename the new states, but I dont want to rename existing ones. Because this will be breaking changes for some users. I will look take a look on your improvements. Thanks so far.

**Comment by foxriver76** [comment]
See GitHub version - if you can confirm that everything works I would publish it to npm.

**Comment by Strunzdesign** [comment]
Yes, I forgot that... renaming existing data points may create problems for existing users. However, you mentioned that the update may not be seamless for existing device entries. Is that correct? That may also provide an opportunity for renaming, but would break existing scripts. Seems to be a bad idea...

Ok I'm going to update and test your latest commit now

**Comment by foxriver76** [comment]
There shouldn't be a problem when upgrading from an old version. The new dps will only show up if the device is deleted once in the object structure. If not everything should behave like before.

I guess having an HM Epaper display is an edge case, but whenever I introduce breaking changes the community isn't amused. ;-) 
I admit, that your name suggestions would be more meaningful but sometimes it's better to stick to the old DP names.

**Comment by Strunzdesign** [comment]
Ok, I updated and removed the meta data again to get rid of the old data points. Looks great, but the default values are still missing. That resulted in:
- I clicked on the empty field of EPAPER_TONE_INTERVAL and immediately a "10" appeared. Good so far, but having it visible at first would be greater.
- I clicked on EPAPER_TONE and selected a sound. One beep, great. It seems it used a "1" for repetitions under the hood.
- Then I clicked on EPAPER_TONE_REPETITIONS and a "0" appeared! Bad things incoming...
- I clicked on EPAPER_TONE to play the sound again, and now the unlimited sequence started.

No idea why the default values (a) do not appear and (b) the INTERVAL is set correctly to 10 but (c) the REPETITIONS are initialized with 0 on first click but appered to be at 1 under the hood before.

Furthermore, please consider removing the three invalid sounds. They have no use and provide just confusion. Even this old script does not mention them:

[https://homematic-forum.de/forum/viewtopic.php?t=31672](https://homematic-forum.de/forum/viewtopic.php?t=31672)

Thanks,
Florian

**Comment by foxriver76** [comment]
Invalid sounds should be removed: https://github.com/ioBroker/ioBroker.hm-rpc/commit/0a60f75195338f462163e295cccd3e2f22466f24#diff-0854083bf65ba3726a2fc46ef4049de3L1343

Default values will only work properly with new js-controller version as mentioned above.

**Comment by Strunzdesign** [comment]
Uh my fault, the dead entries are gone, you are right. No idea what I mixed up. Regarding the controller, I misread your remark "If you are running stable, version is 1.5.14. This would be perfectly fine". I have that version installed, and if it is affected by that issue, then everything is ok.

Go ahead and publish the npm, and thank you very much again for your very fast implementation, I really appreciate that!

Regards,
Florian

**Comment by foxriver76** [comment]
Thanks for the great cooperation. Just published the version. ;-)

**Comment by Strunzdesign** [comment]
I also enjoyed it and somehow I'm looking forward to the [hmip-wrcd](https://de.elv.com/elv-homematic-ip-wandtaster-mit-epaper-statusdisplay-hmip-wrcd-bausatz-250975). LOL seems to be a bigger project to add that, given the little amount of documentation and the existing structure of the source code.

Bis zum nächsten Mal! :-)
Florian
