### ISSUE TITLE
State value to set for "hm-rpc.3.INT0000007.1.SET_TEMPERATURE" has value "30.5" greater than max "30"

### ISSUE THREAD

**Issue by Bratmaxe1981** [ioBroker/ioBroker.hm-rpc#930]
It affects the Homematic radiator thermostats HM-CC-RT-DN which can be set in the range of 5°C-30°C.
In addition, there are the valid values 
​​  4.5°C = OFF = valve     0% open
30.5°C = ON  = valve 100% open.

Please adjust the value range to 4.5-30, then the error in IOBroker should be fixed!

to reproduce you can set the Actor to ON or OFF in der Webinterface and the message will be set!

**Comment by foxriver76** [comment]
Have you tried a force reinit run? afaik, the problem should be fixed. OR maybe it is just very similar.

**Comment by Bratmaxe1981** [comment]
Thanks for the super fast response.
I restarted the adapter and also had the devices read in completely again.
The 1.15.16 is installed

**Comment by 150d** [comment]
... just wanted to add that I'm seeing the same problem here with adapter version v1.15.18. A reinit-config has not helped here. And yes, I'm also getting the messages about the group, not the device.

**Comment by DominikWild** [comment]
@foxriver76  @GermanBluefox 

I can confirm that the problem still exists with adapter version 4.0.0. Reinitializing the configuration does not resolve the issue in my case either. I’m also seeing the messages for the group rather than the individual device.

<html>
<body>

hm-rpc.1 | 2026-09-04 16:10:20.174 | warn | State value to set for "hm-rpc.1.INT0000003.1.SET_TEMPERATURE" has value "30.5" greater than max "30"
-- | -- | -- | --
hm-rpc.1 | 2026-09-04 16:10:14.241 | warn | State value to set for "hm-rpc.1.INT0000002.1.SET_TEMPERATURE" has value "30.5" greater than max "30"
hm-rpc.1 | 2026-09-04 16:10:01.765 | warn | State value to set for "hm-rpc.1.INT0000001.1.SET_TEMPERATURE" has value "30.5" greater than max "30"
hm-rpc.1 | 2026-09-04 16:09:28.004 | warn | State value to set for "hm-rpc.1.INT0000003.1.SET_TEMPERATURE" has value "30.5" greater than max "30"
hm-rpc.1 | 2026-09-04 16:09:27.326 | warn | State value to set for "hm-rpc.1.INT0000004.1.SET_TEMPERATURE" has value "30.5" greater than max "30"
hm-rpc.1 | 2026-09-04 16:09:17.302 | warn | State value to set for "hm-rpc.1.INT0000004.1.SET_TEMPERATURE" has value "30.5" greater than max "30"


</body>
</html>

**Comment by GermanBluefox** [comment]
Fixed in 4.1.1: the CCU declares `SET_TEMPERATURE` of the BidCos heating groups (HM-CC-VG-1) as 5.0 - 30.0, the adapter now uses 4.5 (OFF) - 30.5 (ON) like for the thermostats. The objects of an existing Virtual Devices instance are only updated with a synchronization: after the update, enable "Synchronize objects (once)" in the instance settings once, then the warnings disappear.
